<?php

namespace Database\Seeders;

use App\Models\MenuItem;
use Illuminate\Database\Seeder;

class MenuItemSeeder extends Seeder
{
    /**
     * Run the database seeder.
     */
    public function run(): void
    {
        $menuItems = [
            [
                'name' => 'Classic Espresso',
                'description' => 'Rich, bold espresso shot with perfect crema. The foundation of all great coffee drinks.',
                'category' => 'Hot Coffee',
                'price' => 320.00,
                'image' => 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=400&h=300&fit=crop',
                'preparation_time' => '2-3 min',
                'ingredients' => json_encode(['Espresso beans', 'Water']),
                'allergens' => json_encode([]),
                'calories' => 5,
                'status' => 'active',
            ],
            [
                'name' => 'Cappuccino',
                'description' => 'Perfect balance of espresso, steamed milk, and foam. Traditional Italian favorite.',
                'category' => 'Hot Coffee',
                'price' => 480.00,
                'image' => 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=400&h=300&fit=crop',
                'preparation_time' => '3-4 min',
                'ingredients' => json_encode(['Espresso', 'Steamed milk', 'Milk foam']),
                'allergens' => json_encode(['Dairy']),
                'calories' => 120,
                'status' => 'active',
            ],
            [
                'name' => 'Café Latte',
                'description' => 'Smooth espresso with steamed milk and delicate foam art. Creamy and comforting.',
                'category' => 'Hot Coffee',
                'price' => 520.00,
                'image' => 'https://images.unsplash.com/photo-1561882468-9110e03e0f78?w=400&h=300&fit=crop',
                'preparation_time' => '4-5 min',
                'ingredients' => json_encode(['Espresso', 'Steamed milk', 'Milk foam']),
                'allergens' => json_encode(['Dairy']),
                'calories' => 150,
                'status' => 'active',
            ],
            [
                'name' => 'Caramel Macchiato',
                'description' => 'Rich espresso with vanilla syrup, steamed milk, and caramel drizzle. Sweet perfection.',
                'category' => 'Specialty',
                'price' => 650.00,
                'image' => 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop',
                'preparation_time' => '5-6 min',
                'ingredients' => json_encode(['Espresso', 'Vanilla syrup', 'Steamed milk', 'Caramel sauce']),
                'allergens' => json_encode(['Dairy']),
                'calories' => 250,
                'status' => 'active',
            ],
            [
                'name' => 'Iced Coffee',
                'description' => 'Cold brew coffee served over ice with your choice of milk. Perfect for hot days.',
                'category' => 'Cold Coffee',
                'price' => 580.00,
                'image' => 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&h=300&fit=crop',
                'preparation_time' => '3-4 min',
                'ingredients' => json_encode(['Cold brew coffee', 'Ice', 'Milk']),
                'allergens' => json_encode(['Dairy']),
                'calories' => 80,
                'status' => 'active',
            ],
            [
                'name' => 'Vanilla Frappuccino',
                'description' => 'Blended ice coffee with vanilla flavor and whipped cream. A delightful treat.',
                'category' => 'Cold Coffee',
                'price' => 720.00,
                'image' => 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=400&h=300&fit=crop',
                'preparation_time' => '4-5 min',
                'ingredients' => json_encode(['Coffee', 'Ice', 'Vanilla syrup', 'Whipped cream']),
                'allergens' => json_encode(['Dairy']),
                'calories' => 300,
                'status' => 'active',
            ],
            [
                'name' => 'Ceylon Tea',
                'description' => 'Authentic Sri Lankan black tea with rich flavor and golden color. A local favorite.',
                'category' => 'Tea & Others',
                'price' => 380.00,
                'image' => 'https://images.unsplash.com/photo-1597318374671-96ee162414ca?w=400&h=300&fit=crop',
                'preparation_time' => '3-4 min',
                'ingredients' => json_encode(['Ceylon tea leaves', 'Hot water']),
                'allergens' => json_encode([]),
                'calories' => 2,
                'status' => 'active',
            ],
            [
                'name' => 'Premium Hot Chocolate',
                'description' => 'Rich, creamy hot chocolate made with premium cocoa and topped with marshmallows.',
                'category' => 'Tea & Others',
                'price' => 550.00,
                'image' => 'https://images.unsplash.com/photo-1542990253-a781e04c0082?w=400&h=300&fit=crop',
                'preparation_time' => '4-5 min',
                'ingredients' => json_encode(['Premium cocoa', 'Steamed milk', 'Marshmallows']),
                'allergens' => json_encode(['Dairy']),
                'calories' => 280,
                'status' => 'active',
            ],
            [
                'name' => 'Butter Croissant',
                'description' => 'Flaky, buttery croissant baked fresh daily. Perfect with your morning coffee.',
                'category' => 'Food & Snacks',
                'price' => 280.00,
                'image' => 'https://images.unsplash.com/photo-1555507036-ab794f4afe5b?w=400&h=300&fit=crop',
                'preparation_time' => 'Ready now',
                'ingredients' => json_encode(['Flour', 'Butter', 'Yeast', 'Salt']),
                'allergens' => json_encode(['Gluten', 'Dairy']),
                'calories' => 220,
                'status' => 'active',
            ],
            [
                'name' => 'Club Sandwich',
                'description' => 'Triple-layer sandwich with chicken, bacon, and fresh vegetables. A hearty meal option.',
                'category' => 'Food & Snacks',
                'price' => 850.00,
                'image' => 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=400&h=300&fit=crop',
                'preparation_time' => '8-10 min',
                'ingredients' => json_encode(['Bread', 'Chicken', 'Bacon', 'Lettuce', 'Tomato', 'Mayo']),
                'allergens' => json_encode(['Gluten', 'Dairy']),
                'calories' => 650,
                'status' => 'active',
            ],
            [
                'name' => 'Mocha Delight',
                'description' => 'Rich chocolate and espresso blend topped with whipped cream and cocoa powder. A perfect treat for chocolate lovers.',
                'category' => 'Specialty',
                'price' => 680.00,
                'image' => 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop',
                'preparation_time' => '4-5 min',
                'ingredients' => json_encode(['Espresso', 'Chocolate syrup', 'Steamed milk', 'Whipped cream', 'Cocoa powder']),
                'allergens' => json_encode(['Dairy']),
                'calories' => 320,
                'status' => 'active',
            ],
            [
                'name' => 'Americano',
                'description' => 'Classic black coffee made with espresso and hot water. Simple, strong, and satisfying.',
                'category' => 'Hot Coffee',
                'price' => 420.00,
                'image' => 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=400&h=300&fit=crop',
                'preparation_time' => '2-3 min',
                'ingredients' => json_encode(['Espresso', 'Hot water']),
                'allergens' => json_encode([]),
                'calories' => 10,
                'status' => 'active',
            ],
            [
                'name' => 'Green Tea Latte',
                'description' => 'Smooth matcha green tea blended with steamed milk. A healthy and energizing alternative to coffee.',
                'category' => 'Tea & Others',
                'price' => 590.00,
                'image' => 'https://images.unsplash.com/photo-1597318374671-96ee162414ca?w=400&h=300&fit=crop',
                'preparation_time' => '3-4 min',
                'ingredients' => json_encode(['Matcha powder', 'Steamed milk', 'Sugar']),
                'allergens' => json_encode(['Dairy']),
                'calories' => 180,
                'status' => 'active',
            ],
            [
                'name' => 'Chocolate Muffin',
                'description' => 'Moist chocolate muffin with chocolate chips. Freshly baked daily and perfect with your morning coffee.',
                'category' => 'Food & Snacks',
                'price' => 350.00,
                'image' => 'https://images.unsplash.com/photo-1607958996333-41aef7caefaa?w=400&h=300&fit=crop',
                'preparation_time' => 'Ready now',
                'ingredients' => json_encode(['Flour', 'Chocolate chips', 'Eggs', 'Butter', 'Sugar']),
                'allergens' => json_encode(['Gluten', 'Dairy', 'Eggs']),
                'calories' => 380,
                'status' => 'active',
            ],
            [
                'name' => 'Iced Caramel Latte',
                'description' => 'Refreshing iced latte with caramel syrup and a drizzle of caramel sauce. Perfect for hot days.',
                'category' => 'Cold Coffee',
                'price' => 620.00,
                'image' => 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&h=300&fit=crop',
                'preparation_time' => '3-4 min',
                'ingredients' => json_encode(['Espresso', 'Cold milk', 'Caramel syrup', 'Ice', 'Caramel sauce']),
                'allergens' => json_encode(['Dairy']),
                'calories' => 280,
                'status' => 'active',
            ],
            [
                'name' => 'Avocado Toast',
                'description' => 'Fresh avocado spread on artisan bread, topped with cherry tomatoes and a sprinkle of sea salt.',
                'category' => 'Food & Snacks',
                'price' => 750.00,
                'image' => 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=400&h=300&fit=crop',
                'preparation_time' => '5-6 min',
                'ingredients' => json_encode(['Avocado', 'Artisan bread', 'Cherry tomatoes', 'Sea salt', 'Olive oil']),
                'allergens' => json_encode(['Gluten']),
                'calories' => 420,
                'status' => 'active',
            ],
            [
                'name' => 'Chai Tea Latte',
                'description' => 'Aromatic spiced tea blend with steamed milk and a touch of honey. Warming and comforting.',
                'category' => 'Tea & Others',
                'price' => 540.00,
                'image' => 'https://images.unsplash.com/photo-1597318374671-96ee162414ca?w=400&h=300&fit=crop',
                'preparation_time' => '4-5 min',
                'ingredients' => json_encode(['Chai tea blend', 'Steamed milk', 'Honey', 'Cinnamon']),
                'allergens' => json_encode(['Dairy']),
                'calories' => 200,
                'status' => 'active',
            ],
            [
                'name' => 'Vanilla Latte',
                'description' => 'Smooth espresso with vanilla syrup and perfectly steamed milk. A classic favorite with a sweet twist.',
                'category' => 'Specialty',
                'price' => 580.00,
                'image' => 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=400&h=300&fit=crop',
                'preparation_time' => '3-4 min',
                'ingredients' => json_encode(['Espresso', 'Vanilla syrup', 'Steamed milk']),
                'allergens' => json_encode(['Dairy']),
                'calories' => 220,
                'status' => 'active',
            ],
            [
                'name' => 'Blueberry Pancakes',
                'description' => 'Fluffy pancakes loaded with fresh blueberries, served with maple syrup and butter.',
                'category' => 'Food & Snacks',
                'price' => 890.00,
                'image' => 'https://images.unsplash.com/photo-1506084868230-bb9d95c24759?w=400&h=300&fit=crop',
                'preparation_time' => '8-10 min',
                'ingredients' => json_encode(['Flour', 'Fresh blueberries', 'Eggs', 'Milk', 'Maple syrup', 'Butter']),
                'allergens' => json_encode(['Gluten', 'Dairy', 'Eggs']),
                'calories' => 520,
                'status' => 'active',
            ],
            [
                'name' => 'Iced Matcha Latte',
                'description' => 'Refreshing iced matcha green tea latte with a creamy texture and earthy flavor. Antioxidant-rich and energizing.',
                'category' => 'Cold Coffee',
                'price' => 650.00,
                'image' => 'https://images.unsplash.com/photo-1515823064-d6e0c04616a7?w=400&h=300&fit=crop',
                'preparation_time' => '3-4 min',
                'ingredients' => json_encode(['Matcha powder', 'Cold milk', 'Ice', 'Simple syrup']),
                'allergens' => json_encode(['Dairy']),
                'calories' => 160,
                'status' => 'active',
            ],
        ];

        foreach ($menuItems as $item) {
            MenuItem::create($item);
        }
    }
}
